name: vizdoom-dm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pip
  - pytorch
  - torchvision
  - cpuonly      
  - pip:
      - vizdoom
      - git+https://github.com/alex-petrenko/sample-factory.git@master
